<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>asm</string>
		<string>inc</string>
	</array>
	<key>name</key>
	<string>OUR ASM</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>General perpose register set</string>
			<key>match</key>
			<string>(?i)\br(0|1|2|3|4|5|6|7|8|9|10|11|12|13|14|15)\b</string>
			<key>name</key>
			<string>storage.type.asm</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>All instructions</string>
			<key>match</key>
			<string>(?i)\b(nop|add|sub|sln|shn|res|mov|jmpa|jmpp|jmpn|brnp|brnn|rio|sio|sbr|sri|sra|srvi|srvr|rra|and|addc|cmp)\b</string>
			<key>name</key>
			<string>keyword.operator.asm</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Comment line</string>
			<key>match</key>
			<string>(;)(\s|\S)*</string>
			<key>name</key>
			<string>comment.line.asm</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Single-line string</string>
			<key>match</key>
			<string>(^|\s)"[\w\s\W]*"($|\s)</string>
			<key>name</key>
			<string>string.asm</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Single-line string</string>
			<key>match</key>
			<string>(^|\s)\'[\w\s\W]*\'($|\s)</string>
			<key>name</key>
			<string>string.asm</string>
		</dict>
		<dict>
			<key>PC pointer</key>
			<string>Goto tag</string>
			<key>match</key>
			<string>(^|\s)\{[\w\s\W]*\}($|\s)</string>
			<key>name</key>
			<string>string.asm</string>
		</dict>
		<dict>
			<key>RAM adress</key>
			<string>Fixed adress in the ram</string>
			<key>match</key>
			<string>(^|\s)\[[\w\s\W]*\]($|\s)</string>
			<key>name</key>
			<string>storage.type.asm</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Hex number constant</string>
			<key>match</key>
			<string>(?i)\b(0x(\d|[A-F])+)\b</string>
			<key>name</key>
			<string>constant.numeric.asm</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Dec number constant</string>
			<key>match</key>
			<string>\b(0|1|2|3|4|5|6|7|8|9|\d+)\b</string>
			<key>name</key>
			<string>constant.numeric.asm</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.asm</string>
	<key>uuid</key>
	<string>97b6acae-cfc1-4c14-b572-c51987e1e023</string>
</dict>
</plist>
